#!/usr/bin/env bash

set -o pipefail

PID=$$
VOLUME_NAME=$1
DOCKER_SHELL_IMAGE=busybox
SRC_FILE_NAME="${VOLUME_NAME}.tar"
SRC_FILE_NAME=${2:-$DEST_FILE_NAME}
DOCKER_BIN=`command -v docker || which docker`

if [[ "$DOCKER_BIN" == "" ]]; then
    echo "Docker binary not found. Please install docker first."
    echo "Can use: curl https://get.docker.com | sh"
    exit 1
fi

if [ -z "$VOLUME_NAME" ]; then
  echo "Usage: $0 <volume name> (<source file name>)"
  exit 1
fi

$DOCKER_BIN volume inspect $VOLUME_NAME > /dev/null 2>&1 || {
  echo "Volume $VOLUME_NAME does not exist. Create volume ..."
  $DOCKER_BIN volume create $VOLUME_NAME
}

read -p "Are you sure you want to import volume $VOLUME_NAME from $SRC_FILE_NAME.tgz ? [y/N] " -n 1 -r

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo
  echo "Aborting."
  exit 1
fi

echo
echo "Importing volume $VOLUME_NAME from $SRC_FILE_NAME.tgz ..."
$DOCKER_BIN run -v $VOLUME_NAME:/data --name import_volume_$PID busybox /bin/sh
$DOCKER_BIN run --rm --volumes-from import_volume_$PID -v $(pwd):/importd busybox sh -c "cd /data && tar xvf /importd/$SRC_FILE_NAME.tgz --strip 1"
$DOCKER_BIN rm import_volume_$PID